[package]
name = "rptadv-samplerate-adapter"
version = "0.1.0-alpha.2"
edition = "2024"
rust-version = "1.85"
license = "GPL-2.0-only"
description = "libsamplerate adapter for rpt_advanced"
homepage = "https://github.com/cpeter1207/rptadv-samplerate-adapter"
repository = "https://github.com/cpeter1207/rptadv-samplerate-adapter"
publish = false

[lib]
name = "rptadv_samplerate_adapter"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
debug = 1
lto = "thin"
panic = "abort"
